on: push 
name: CI/CD 
jobs:
  FTP-Deploy-Action:
    name: CI&CD 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@master 
        with:
          fetch-depth: 2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2.1.4 
        with:
          node-version: '18.x' 

      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }} 

      - name: Install pnpm
        run: npm i pnpm -g

      - name: Install Dependencies
        # if: steps.cache.outputs.cache-hit != 'true' 
        run: pnpm i 

      - name: Build Packages
        run: pnpm run build 
        

      # - name: reset git
      #   run: git reset --hard

      # - name: FTP-Deploy-Action
      #   uses: SamKirkland/FTP-Deploy-Action@3.1.1
      #   with:
      #     ftp-server: sftp://${{ secrets.FTP_IP }}/usr/local/src/pre/home 
      #     ftp-username: ${{ secrets.FTP_USERNAME }} 
      #     ftp-password: ${{ secrets.FTP_PASSWORD }} 
      #     git-ftp-args: --insecure
      #     local-dir: ./.vitepress/dist 

